# Wir haben einen Google-Kalender mit allen Terminen der Feuerwehr (Übungen, Vereinsaktivitäten, ...)
# Wir haben in der aktiven Wehr zwei Löschzüge
# Jeder soll jeden Termin genau einmal im aPager haben
# Jeder soll nur die Übungsbenachrichtigungen bekommen, die für ihn relevant sind (je nach Zug-Zugehörigkeit)

# Kriterium Übung: Das Wort Übung kommt vor
# Kriterium 1. Zug: Das Wort Übung kommt vor, endet auf 'Zug 1'
# Kriterium 2. Zug: Das Wort Übung kommt vor, endet auf 'Zug 2'
# Kriterium Gemeinschaftsübung: Das Wort Übung kommt vor, endet nicht auf 'Zug 1' oder 'Zug 2'

# Kalender ohne Übungen und ohne Benachrichtigungen
ffw_no_drills_no_alarms:
   ical_url: #{ICAL_URL}
   api_key: #{API_KEY}
   timezone: #{TZ}
   rules:
     - field: summary
       operator: not-matches
       val: '/übung/i'
   alarms:
     clear_existing: true

# Kalender mit Übungen für die gesamte Wehr mit Benachrichtigungen
ffw_only_collective_drills_with_alarms:
   ical_url: #{ICAL_URL}
   api_key: #{API_KEY}
   timezone: #{TZ}
   rules:
     - field: summary
       operator: matches
       val: '/übung/i'
     - field: summary
       operator: not-matches
       val: '/zug [12]$/i'
   alarms:
     clear_existing: true
     triggers:
       - 1 day
       - 5 days

# Kalender mit Übungen für den ersten Zug mit Benachrichtigungen
ffw_drills_brigade_1_with_alarms:
   ical_url: #{ICAL_URL}
   api_key: #{API_KEY}
   timezone: #{TZ}
   rules:
     - field: summary
       operator: matches
       val: '/übung/i'
     - field: summary
       operator: matches
       val: '/zug 1$/i'
   alarms:
     clear_existing: true
     triggers:
       - 1 day
       - 5 days
       
# Kalender mit Übungen für den ersten Zug ohne Benachrichtigungen
ffw_drills_brigade_1_no_alarms:
   ical_url: #{ICAL_URL}
   api_key: #{API_KEY}
   timezone: #{TZ}
   rules:
     - field: summary
       operator: matches
       val: '/übung/i'
     - field: summary
       operator: matches
       val: '/zug 1$/i'
   alarms:
     clear_existing: true
       
# Kalender mit Übungen für den zweiten Zug mit Benachrichtigungen
ffw_drills_brigade_2_with_alarms:
   ical_url: #{ICAL_URL}
   api_key: #{API_KEY}
   timezone: #{TZ}
   rules:
     - field: summary
       operator: matches
       val: '/übung/i'
     - field: summary
       operator: matches
       val: '/zug 2$/i'
   alarms:
     clear_existing: true
     triggers:
       - 1 day
       - 5 days
       
# Kalender mit Übungen für den zweiten Zug ohne Benachrichtigungen
ffw_drills_brigade_2_no_alarms:
   ical_url: #{ICAL_URL}
   api_key: #{API_KEY}
   timezone: #{TZ}
   rules:
     - field: summary
       operator: matches
       val: '/übung/i'
     - field: summary
       operator: matches
       val: '/zug 2$/i'
   alarms:
     clear_existing: true
