version: '3.7'

services:
  fe2_calendar:
    image: odin568/fe2_calendar:latest
    container_name: fe2_calendar
    ports:
      - "8084:8000"
    restart: always
    healthcheck:
      test: curl --insecure --fail http://localhost:8000/ || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - ICAL_FILTER_PROXY_API_KEY=<yourapikey>
      - ICAL_FILTER_PROXY_ICAL_URL=<calendarurl>
