version: '3.7'

services:
  fe2_calendar:
    image: odin568/fe2_calendar:latest
    container_name: fe2_calendar
    ports:
      - "8000:8000"
    restart: always
    environment:
      - API_KEY=<yourapikey>
      - ICAL_URL=<calendarurl>
