# Wir haben einen Google-Kalender mit allen Terminen der Feuerwehr (Übungen, Vereinsaktivitäten, ...)
# Wir haben in der aktiven Wehr zwei Löschzüge
# Jeder soll jeden Termin genau einmal im aPager haben
# Jeder soll nur die Übungsbenachrichtigungen bekommen, die für ihn relevant sind (je nach Zug-Zugehörigkeit)

##### Terminpattern #####

## Gruppenübung Zug 1 Gruppe 1
## Gruppenübung Zug 1 Gruppe 2
## Zugübung Zug 1

## Gruppenübung Zug 2 Gruppe 3
## Gruppenübung Zug 2 Gruppe 4
## Zugübung Zug 2

## Gemeinschaftsübung

#########################

# Kalender ohne Übungen und ohne Benachrichtigungen
ffw_no_drills_no_alarms:
   ical_url: ${ICAL_FILTER_PROXY_ICAL_URL}
   api_key: ${ICAL_FILTER_PROXY_API_KEY}
   timezone: ${ICAL_FILTER_PROXY_TIMEZONE}
   rules:
     - field: summary
       operator: not-matches
       val: '/übung/i'
   alarms:
     clear_existing: true

# Kalender mit Übungen für die gesamte Wehr mit Benachrichtigungen
ffw_only_collective_drills_with_alarms:
   ical_url: ${ICAL_FILTER_PROXY_ICAL_URL}
   api_key: ${ICAL_FILTER_PROXY_API_KEY}
   timezone: ${ICAL_FILTER_PROXY_TIMEZONE}
   rules:
     - field: summary
       operator: matches
       val: '/gemeinschaftsübung/i'
   alarms:
     clear_existing: true
     triggers:
       - 1 day
       - 5 days

# Kalender mit Übungen für den ersten Zug mit Benachrichtigungen
ffw_drills_brigade_1_with_alarms:
   ical_url: ${ICAL_FILTER_PROXY_ICAL_URL}
   api_key: ${ICAL_FILTER_PROXY_API_KEY}
   timezone: ${ICAL_FILTER_PROXY_TIMEZONE}
   rules:
     - field: summary
       operator: matches
       val: '/(gruppen|zug)übung/i'
     - field: summary
       operator: matches
       val: '/zug 1/i'
   alarms:
     clear_existing: true
     triggers:
       - 1 day
       - 5 days
       
# Kalender mit Übungen für den ersten Zug ohne Benachrichtigungen
ffw_drills_brigade_1_no_alarms:
   ical_url: ${ICAL_FILTER_PROXY_ICAL_URL}
   api_key: ${ICAL_FILTER_PROXY_API_KEY}
   timezone: ${ICAL_FILTER_PROXY_TIMEZONE}
   rules:
     - field: summary
       operator: matches
       val: '/(gruppen|zug)übung/i'
     - field: summary
       operator: matches
       val: '/zug 1/i'
   alarms:
     clear_existing: true
       
# Kalender mit Übungen für den zweiten Zug mit Benachrichtigungen
ffw_drills_brigade_2_with_alarms:
   ical_url: ${ICAL_FILTER_PROXY_ICAL_URL}
   api_key: ${ICAL_FILTER_PROXY_API_KEY}
   timezone: ${ICAL_FILTER_PROXY_TIMEZONE}
   rules:
     - field: summary
       operator: matches
       val: '/(gruppen|zug)übung/i'
     - field: summary
       operator: matches
       val: '/zug 2/i'
   alarms:
     clear_existing: true
     triggers:
       - 1 day
       - 5 days
       
# Kalender mit Übungen für den zweiten Zug ohne Benachrichtigungen
ffw_drills_brigade_2_no_alarms:
   ical_url: ${ICAL_FILTER_PROXY_ICAL_URL}
   api_key: ${ICAL_FILTER_PROXY_API_KEY}
   timezone: ${ICAL_FILTER_PROXY_TIMEZONE}
   rules:
     - field: summary
       operator: matches
       val: '/(gruppen|zug)übung/i'
     - field: summary
       operator: matches
       val: '/zug 2/i'
   alarms:
     clear_existing: true
